#!/usr/bin/env bash
# CodeRAG End-to-End Integration Test
# Tests the full workflow against real repositories

PASSED=0
FAILED=0
TOTAL=0

pass() { PASSED=$((PASSED + 1)); TOTAL=$((TOTAL + 1)); echo "  ✅ $1"; }
fail() { FAILED=$((FAILED + 1)); TOTAL=$((TOTAL + 1)); echo "  ❌ $1"; }
check() {
    local desc="$1"
    shift
    if "$@" >/dev/null 2>&1; then
        pass "$desc"
    else
        fail "$desc"
    fi
}

# Helper: run command, capture output, grep pattern
run_grep() {
    local pattern="$1"
    shift
    local output
    output=$("$@" 2>&1)
    echo "$output" | grep -qi "$pattern"
}

echo "═══════════════════════════════════════════"
echo "  CodeRAG End-to-End Integration Tests"
echo "═══════════════════════════════════════════"
echo ""

# Use Slim framework as test repo (small, fast)
TEST_REPO="/tmp/e2e-slim"
if [ ! -d "$TEST_REPO" ]; then
    echo "📥 Cloning test repository..."
    git clone --depth 1 https://github.com/slimphp/Slim.git "$TEST_REPO" 2>/dev/null
fi

# Clean any previous graph data for a fresh test
rm -rf "$TEST_REPO/.codegraph"
rm -f "$TEST_REPO/CLAUDE.md"

echo ""
echo "── 1. Core Pipeline ──────────────────────"
check "Parse codebase" run_grep "completed\|pipeline" coderag parse "$TEST_REPO"

# All subsequent commands run from within the test repo directory
cd "$TEST_REPO" || exit 1

check "Show graph info" run_grep "node\|total\|database" coderag info
check "Query symbols" run_grep "app" coderag query App
check "Find usages" run_grep "route\|usage" coderag find-usages Route
check "Detect frameworks" run_grep "framework\|detected\|no framework" coderag frameworks
check "Cross-language analysis" run_grep "cross-language\|connection\|endpoint" coderag cross-language

echo ""
echo "── 2. Graph Analysis ─────────────────────"
check "Analyze symbol" run_grep "impact\|affected\|graph\|analysis" coderag analyze App
check "Dependency graph" run_grep "depend\|graph\|app" coderag deps App
check "Architecture overview" run_grep "communit\|pagerank\|node\|overview" coderag architecture

echo ""
echo "── 3. File Context ───────────────────────"
PHP_FILE=$(find "$TEST_REPO/Slim" -name '*.php' -type f | head -1)
check "File context" run_grep "symbol\|file\|method\|class" coderag file-context "$PHP_FILE"

echo ""
echo "── 4. Smart Launcher ─────────────────────"
# dry-run: capture full output to avoid SIGPIPE killing CLAUDE.md generation
DRY_OUTPUT=$(coderag launch . --dry-run 2>&1)
if echo "$DRY_OUTPUT" | grep -qi "state\|context\|dry.run\|ready"; then
    pass "Launch dry-run"
else
    fail "Launch dry-run"
fi

# Verify CLAUDE.md was generated by dry-run
if [ -f "$TEST_REPO/CLAUDE.md" ]; then
    pass "CLAUDE.md generated"
else
    fail "CLAUDE.md not found"
fi

# context-only outputs context to stdout
CTX_OUTPUT=$(coderag launch . --context-only 2>&1)
CTX_LINES=$(echo "$CTX_OUTPUT" | wc -l)
if [ "$CTX_LINES" -gt 5 ]; then
    pass "Launch context-only ($CTX_LINES lines)"
else
    fail "Launch context-only (only $CTX_LINES lines)"
fi

echo ""
echo "── 5. Session Memory ─────────────────────"
check "Session list" run_grep "session\|no session\|found" coderag session list
check "Session context" run_grep "context\|no active\|item" coderag session context

echo ""
echo "── 6. Cost Benchmarking ──────────────────"
check "Cost benchmark" run_grep "saving\|cost\|token\|benchmark" coderag benchmark .

echo ""
echo "── 7. Update System ──────────────────────"
check "Update check" run_grep "version" coderag update check
check "Update config" run_grep "auto\|channel\|interval" coderag update config

echo ""
echo "═══════════════════════════════════════════"
echo "  Results: $PASSED passed, $FAILED failed, $TOTAL total"
echo "═══════════════════════════════════════════"

if [ "$FAILED" -eq 0 ]; then
    echo "🎉 All tests passed!"
    exit 0
else
    echo "💥 Some tests failed!"
    exit 1
fi
